### ADD /var/ossec/etc/ossec.conf
<ossec_config>
  <command>
    <name>yara_linux</name>
    <executable>yara.sh</executable>
    <extra_args>-yara_path /usr/bin -yara_rules /var/ossec/yara_rules/yara_rules.yar</extra_args>
<!--    <extra_args>-yara_path /usr/bin -yara_rules /var/ossec/yara_rules/*</extra_args> -->
    <timeout_allowed>no</timeout_allowed>
  </command>

  <active-response>
    <disabled>no</disabled>
    <command>yara_linux</command>
    <location>local</location>
    <rules_id>100200,100201,100203,100202,100204,100205,100206,100207,100208,100209,100210,100211,100212,100213,100214,100215,100216,100217</rules_id>
  </active-response>
</ossec_config>
